# Generated by Django 5.1.5 on 2025-10-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_ingredientimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
